"""Population pyramid preparation service for Feature Card 3."""

from __future__ import annotations

import pandas as pd
from pandas import DataFrame


AGE_BANDS: tuple[tuple[str, str], ...] = (
    ("age_below_10", "Below 10"),
    ("age_10_19", "10-19"),
    ("age_20_29", "20-29"),
    ("age_30_39", "30-39"),
    ("age_40_49", "40-49"),
    ("age_50_59", "50-59"),
    ("age_60_plus", "60+"),
)


def _safe_float(value: object) -> float:
    try:
        parsed = float(value)
        return parsed if pd.notna(parsed) else 0.0
    except Exception:
        return 0.0


def prepare_population_pyramid_payload(canonical_df: DataFrame, selected_year: int) -> dict[str, object]:
    """Build an estimated population pyramid payload for a selected year.

    Since source data has age shares and aggregate male/female shares (without age x gender
    cross-tab), each age band is proportionally split by overall gender ratio.
    """
    if canonical_df.empty:
        raise ValueError("Canonical demographic data is empty; cannot build pyramid.")

    year_df = canonical_df[canonical_df["report_year"] == selected_year]
    if year_df.empty:
        raise ValueError(f"Year {selected_year} not found for population pyramid payload.")

    row = year_df.iloc[-1]

    male = _safe_float(row.get("gender_male"))
    female = _safe_float(row.get("gender_female"))
    gender_total = male + female
    male_ratio = (male / gender_total) if gender_total > 0 else 0.5
    female_ratio = (female / gender_total) if gender_total > 0 else 0.5

    age_groups: list[str] = []
    male_values: list[int] = []
    female_values: list[int] = []

    for column, label in AGE_BANDS:
        age_value = max(0.0, _safe_float(row.get(column)))
        est_male = int(round(age_value * male_ratio))
        est_female = int(round(age_value * female_ratio))

        age_groups.append(label)
        male_values.append(est_male)
        female_values.append(est_female)

    return {
        "report_year": int(selected_year),
        "age_groups": age_groups,
        "male_values": male_values,
        "female_values": female_values,
        "is_estimated": True,
        "estimation_note": (
            "Estimated pyramid generated by splitting age-band totals using "
            "the overall male/female ratio for the selected year."
        ),
    }


__all__ = ["prepare_population_pyramid_payload"]

